# Generated by Django 4.2.17 on 2025-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
