# Generated by Django 4.2.17 on 2025-01-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_excerpt_story_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
