# Generated by Django 4.2.17 on 2025-01-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='excerpt',
        ),
    ]
